### PR TITLE
added checker for creating duplicate playlist

### PR DESCRIPTION
**Pull request by utkarsh4321**
Hii @RyanRussell00 thanks for this great opportunity. I worked on issue #7. And added some fixes on the basis of your requirement. Can you please review my PR? And let me know if there is any problem so I will try to fix it asap.

### CODE REVIEW

**Review by RyanRussell00 — CHANGES_REQUESTED** [review]
This looks good! Just one small change: When the user selects "Filter Explicit" it should be considered a new playlist.

Expected behavior: The user creates and saves a playlist. Then they select "filter explicit". When they save again, they shouldn't be notified that this is a duplicate (since the explicit and non-explicit are 2 different playlists).

Let me know if you have any questions. Thanks for this!

**Comment by utkarsh4321** [comment]
Hii @RyanRussell00 I wanna ask one thing why you use explicit button event handler into two places.  Can you explain to me about it?
image
The first one inside playlist-button event handler and the second one below this handler you can see into above screenshot

**Comment by utkarsh4321** [comment]
One thing more if anyone clicked on recommendation then need to reset flag for both explicit playlist and non-explicit playlist

**Comment by RyanRussell00** [comment]
@utkarsh4321 

1. The explicit function inside the playlist button was leftover from the merge conflict. Thanks for catching that! I've removed it and updated master.

2. Whenever new recommendations are generated it should reset both flags: explicit and non-explicit. This is because when they click on "get recommendations", an entirely new playlist is curated for them.

Let me know if you have any more questions

**Comment by utkarsh4321** [comment]
Hii @RyanRussell00 I fix the explicit playlist confirmation problem can you please review my PR. If there is any problem then tell me. I will try to fix asap.

**Comment by utkarsh4321** [comment]
Hii @RyanRussell00 is there any problem with it can you please tell me so I will fix it.

**Review by RyanRussell00 — APPROVED** [review]
This is amazing! Thank you for this contribution!
There are a few minor touch-ups (grammar) but I'll handle that in master branch.

**Pull request merged**
