### PR TITLE
Added more customized inputs for recommendations

### LINKED ISSUE #20: Add more customized inputs for recommendations
The [Spotify Web API for recommendations](https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/) offers the option to add more inputs, such as:
- acousticness
- instrumentalness
- speechiness
- tempo
- valence (Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).)

**Note:** These should all be optional inputs.

### PR DESCRIPTION
**Pull request by sonamdh1**
Added optional inputs such as:
- acousticness
- instrumentalness
- speechiness
- tempo
- valence

Added validation and hint-text for the fields.

### CODE REVIEW

**Comment by RyanRussell00** [comment]
@sonamdh1 This looks good! The only thing missing is sending the extra parameters to the Spotify API in the app.js but I can handle that in another branch since I know that testing it can get difficult.
I'll merge this into master as soon as I get the chance to handle the merge conflicts and add the app.js stuff.

Thanks!

**Review by RyanRussell00 — APPROVED** [review]

**Comment by sonamdh1** [comment]
@RyanRussell00 Great! Actually I can add that part, can add it to this PR itself.

**Comment by RyanRussell00** [comment]
@sonamdh1 That would be great if you could! 
I tried doing it last night but for some reason your code isn't working on my machine, the index.html isn't displaying the #step-2 div.
I think it could have been due to the merge conflicts as well.

If you could handle the merge conflicts and update the apo.js that would be awesome, thanks!
Let me know if you need help

**Comment by sonamdh1** [comment]
@RyanRussell00 I have integrated the additional API params in api.js. I have verified the working and the URL getting constructed. Will try to resolve the merge conflicts as well.

**Comment by sonamdh1** [comment]
@RyanRussell00 I have resolved the merge conflicts. I have verified the functionality of the PR.
Can you please verify if the rest of the functionality is working fine as well like "Filter explicit content"?
Let me know if any change is required.

**Comment by RyanRussell00** [comment]
@sonamdh1 This is fantastic! Thank you for this!

**Pull request merged**
